Configure LXD when creating a target rather than in the postinst.
Otherwise we get this exception on bionic:

  pylxd.exceptions.LXDAPIException: The "default" storage pool doesn't exist